# Generated by Django 2.1.14 on 2021-11-28 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_heroinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booktest.BookInfo'),
        ),
    ]
