# Generated by Django 2.1.14 on 2022-05-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='bput_date',
            new_name='bpub_date',
        ),
    ]
