# Generated by Django 2.1.4 on 2019-12-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gf', models.CharField(max_length=32)),
                ('cid', models.CharField(max_length=32)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Author')),
            ],
            options={
                'db_table': 'authordetail',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booktype', models.CharField(max_length=32, null=True)),
                ('pub_date', models.DateField()),
                ('authors', models.ManyToManyField(db_table='book2author', to='app01.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'publish',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.Publish'),
        ),
    ]
