# Generated by Django 2.1.4 on 2019-12-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_authors'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
