# Generated by Django 2.1.1 on 2019-01-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
