# Generated by Django 2.1.4 on 2022-05-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='domaininfo',
            name='dname',
            field=models.CharField(max_length=50),
        ),
    ]
