# Generated by Django 2.1.4 on 2022-05-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanage', '0002_auto_20220513_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whoiscompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'whoiscompany',
            },
        ),
        migrations.RemoveField(
            model_name='domaininfo',
            name='isDelete',
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='isDeploy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whoiscompany',
            name='wdomaininfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainmanage.DomainInfo'),
        ),
    ]
