# Generated by Django 2.1.4 on 2022-05-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanage', '0003_auto_20220516_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoiscompany',
            name='wdomaininfo',
        ),
        migrations.AddField(
            model_name='domaininfo',
            name='dwhoiscompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domainmanage.Whoiscompany'),
        ),
    ]
