# Generated by Django 2.1.4 on 2022-05-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainmanage', '0004_auto_20220516_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoiscompany',
            name='url',
        ),
    ]
