# Generated by Django 2.1.4 on 2020-07-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_myapp_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cat',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'manufacturer',
            },
        ),
        migrations.AlterField(
            model_name='myapp_person',
            name='first_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Manufacturer'),
        ),
    ]
