# Generated by Django 2.1.4 on 2020-07-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200720_1543'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
    ]
